[build]
publish = "/"
command = """
  rustup toolchain install stable && \
    cargo install rust-script && \
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.39/quarto-1.6.39-linux-amd64.tar.gz && \
    mkdir ~/opt && tar -C ~/opt -xvzf quarto-1.6.39-linux-amd64.tar.gz && \
    mkdir ~/.local/bin && ln -s ~/opt/quarto-1.6.39/bin/quarto ~/.local/bin/quarto && \
    ( echo ""; echo 'export PATH=$PATH:~/.local/bin\n' ; echo "" ) >> ~/.profile && source ~/.profile && \
    quarto check && \
    npm run build
"""