name: Quarto Render

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render-quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("knitr", "rmarkdown"), repos="https://cloud.r-project.org/")'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Jupyter
      run: |
        python3 -m pip install jupyter

    - name: Run Quarto Render Script
      run: |
        chmod +x src/quarto/quarto_render.sh
        ./src/quarto/quarto_render.sh

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github@renanperes.com"
        git config --local user.name "renan-peres"
        git add .
        git commit -m "Render Quarto documents" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}