name: Quarto Render

on:
  schedule:
    - cron: '0 10 * * 1-5'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  render-quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - uses: actions/checkout@v4

    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.8.25

    - name: Install Linux dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        libudunits2-dev libgdal-dev gdal-bin libgeos-dev libproj-dev \
        libssl-dev libcurl4-openssl-dev libxml2-dev cmake

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.3'

    - uses: actions/cache@v4
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: ${{ runner.os }}-renv-

    - name: Initialize R environment
      working-directory: src/mban/quarto
      run: |
        Rscript -e 'install.packages("renv"); renv::consent(TRUE); renv::restore()'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
        cache: pip
        cache-dependency-path: src/mban/quarto/requirements.txt

    - name: Render Quarto documents
      working-directory: src/mban/quarto
      run: ./quarto_render.sh

    - name: Commit and push
      run: |
        git config user.email "github@renanperes.com"
        git config user.name "renan-peres"
        git add .
        git commit -m "Render Quarto documents" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}