name: Quarto Render

on:
  schedule:
    - cron: '0 10 * * 1-5'  # Every weekday (Mon-Fri) at 10 AM
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render-quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.3.450

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/renv
          ~/.cache/R
          ${{ runner.temp }}/Library
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Initialize R environment
      run: |
        cd src/dev/quarto
        mkdir -p ~/.local/share/renv
        chmod -R 777 ~/.local/share/renv
        echo "RENV_PATHS_CACHE=~/.local/share/renv" >> $GITHUB_ENV
        Rscript -e 'install.packages("renv")'
        Rscript -e 'renv::consent(provided = TRUE)'
        Rscript -e 'renv::restore()'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: 'src/dev/quarto/requirements.txt'

    - name: Run Quarto Render Script
      run: |
        cd src/dev/quarto
        chmod +x quarto_render.sh
        ./quarto_render.sh

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github@renanperes.com"
        git config --local user.name "renan-peres"
        git add .
        git commit -m "Render Quarto documents" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}